### ISSUE TITLE
[FR] - Configurable command name

### ISSUE THREAD

**Issue by LurgenAU** [Lorias-Jak/LoriTime#33]
It would be great to allow administrators to configure the command name. /loritime isn't intuitive to players, so an alias is pretty much required for player convenience. Otherwise great little plugin, very nicely done!

**Comment by Lorias-Jak** [comment]
Thank you for the suggestion, I will work it in. 
Do you have a wish that should be set as default in the config?

**Comment by Lorias-Jak** [comment]
A few moments of thinking, do you run the plugin on a proxy or bukkit? The info would be helpful because bukkit does not allow dynamic changes to aliases without some reflections. Within Velocity or Bungee it should be no problem to add more aliases than the existing one

**Comment by LurgenAU** [comment]
I run the plugin on Velocity, and would suggest that aliases on back-end servers are less of an issue thanks to Spigot's neat little commands.yml aliasing system.

Maybe set the initial command to /playtime? That leads to a bunch of intuitive (I think) subcommands such as:
- [no argument] = Help, ideally drawn from a language config so it too can be personalised
- [check] = my playing time balances
- [check] [playername] = checks another player
- [top] = leaderboards (can these see what server players are on, for a per-server leaderboard?)
- [set/add/delete] [playername] = adjust player balances
- [reload] = reload plugin
etc.

Potentially quite a lot of shuffling about though, so just friendly suggestions. I find it's best to contain as much as possible under a single generic command, rather than multiple commands.

**Comment by sluhtie** [comment]
I would also hightlu suggest this feature. Would be very nice if this is implemented.

**Comment by Lorias-Jak** [comment]
It's on my list! Just don't have the time right now, my studies are taking a lot of time right now. Will implement it as soon as i have the time

**Comment by Lorias-Jak** [comment]
Sorry, it took me a little longer to find the time. 

With the next update the desired feature will come, I'll test everything this weekend. Should be ready on Sunday

**Comment by Lorias-Jak** [comment]
Optional you can download the artifact from here, just make sure to regenerate your config files

https://github.com/Lorias-Jak/LoriTime/actions/runs/9038374255

**Comment by Lorias-Jak** [comment]
https://modrinth.com/plugin/loritime/versions
